services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: arxiv_backend
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_started
      qdrant:
        condition: service_started
    env_file: .env
    environment:
      - MONGO_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-pass}@mongo:27017
      - QDRANT_URL=http://qdrant:6333
      - VECTOR_SIZE=${VECTOR_SIZE}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend/src:/app/src
      - ./logs:/app/logs
    networks:
      - arxiv_net

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: arxiv_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file: .env
    environment:
      - BACKEND_API_URL=http://backend:8000
    networks:
      - arxiv_net
    volumes:
      - ./frontend/src:/app/src

  mongo:
    image: mongo:7.0
    container_name: arxiv_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-pass}
    volumes:
      - ./data/mongo_db:/data/db
    networks:
      - arxiv_net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: arxiv_qdrant
    restart: always
    volumes:
      - ./data/qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - arxiv_net

networks:
  arxiv_net:
    driver: bridge