[project]
name = "arxiv-daily-digest"
version = "0.0.1"
description = "An AI Agent powered by LangGraph to fetch, summarize, and discuss new papers from arXiv daily."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arxiv>=2.4.0",
    "dotenv>=0.9.9",
    "pydantic>=2.12.5",
]